---
kind: pipeline
name: rust-stable

volumes:
  - name: cargo-cache
    host:
      path: /var/lib/cargo-cache

services:
  - name: db
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: webalert
      POSTGRES_PASSWORD: webalert
      POSTGRES_DB: webalert_development

steps:
- name: build
  image: rust:1.45
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build

- name: test
  image: rust:1.45
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test
    - git rev-parse HEAD > .tags

- name: test migrate up
  image: rust:1.45
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    RUST_LOG: debug
    CARGO_HOME: /tmp/cargo-cache
    POSTGRES_URL: postgresql://webalert:webalert@db/webalert_development
  commands:
    - cargo run -- db migrate up

---
kind: pipeline
name: rust-nightly

volumes:
  - name: cargo-cache
    host:
      path: /var/lib/cargo-cache

services:
  - name: db
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: webalert
      POSTGRES_PASSWORD: webalert
      POSTGRES_DB: webalert_development

steps:
- name: build
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build
- name: test
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test
- name: test migrate up
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    RUST_LOG: debug
    CARGO_HOME: /tmp/cargo-cache
    POSTGRES_URL: postgresql://webalert:webalert@db/webalert_development
  commands:
    - cargo run -- db migrate up
---
kind: signature
hmac: eb6e400011fb2015900f3452512afb1ef1684a07b8059dff95435b4dc7e625dc

...
