---
kind: pipeline
name: rust-stable

volumes:
  - name: cargo-cache
    host:
      path: /var/lib/cargo-cache

steps:
- name: postgres
  image: postgres:12.3-alpine
  detach: true
  environment:
    POSTGRES_DB: webalert_development
    POSTGRES_USER: webalert
    POSTGRES_PASSWORD: webalert

- name: build
  image: rust:1.45
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build

- name: test
  image: rust:1.45
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test
    - git rev-parse HEAD > .tags

- name: test migrate up
  image: rust:1.45
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    RUST_LOG: debug
    CARGO_HOME: /tmp/cargo-cache
    POSTGRES_URL: postgresql://webalert:webalert@postgres/webalert_development
  commands:
    - cargo run -- db migrate up

- name: test migrate down
  image: rust:1.45
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    RUST_LOG: debug
    CARGO_HOME: /tmp/cargo-cache
    POSTGRES_URL: postgresql://webalert:webalert@postgres/webalert_development
  commands:
    - cargo run -- db migrate down 0

- name: run coverage tests
  image: rust:1.45
  privileged: true
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - |
      apt update && \
        apt install -y cmake binutils-dev libcurl4-openssl-dev libiberty-dev libelf-dev libdw-dev jq
      cargo install cargo-kcov
      cargo kcov --print-install-kcov-sh | sh
      cargo kcov --all -v

- name: upload code coverage
  image: rust:1.45
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
    - bash -c "bash <(curl -s https://codecov.io/bash)"

---
kind: pipeline
name: rust-nightly

volumes:
  - name: cargo-cache
    host:
      path: /var/lib/cargo-cache

steps:
- name: postgres
  image: postgres:12.3-alpine
  detach: true
  environment:
    POSTGRES_USER: webalert
    POSTGRES_PASSWORD: webalert
    POSTGRES_DB: webalert_development

- name: build
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build

- name: test
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test

- name: test migrate up
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    RUST_LOG: debug
    CARGO_HOME: /tmp/cargo-cache
    POSTGRES_URL: postgresql://webalert:webalert@postgres/webalert_development
  commands:
    - cargo run -- db migrate up

- name: test migrate down
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    RUST_LOG: debug
    CARGO_HOME: /tmp/cargo-cache
    POSTGRES_URL: postgresql://webalert:webalert@postgres/webalert_development
  commands:
    - cargo run -- db migrate down 0

---
kind: signature
hmac: b6dfa4fb7dc17491ee54c9af48bf0298ce8cb6fe4fe19955aa0f03614c56cae7

...
