---
kind: pipeline
name: rust-stable

volumes:
  - name: cargo-cache
    host:
      path: /var/lib/cargo-cache

steps:
- name: postgres
  image: postgres:12.3-alpine
  detach: true
  environment:
    POSTGRES_DB: webalert_development
    POSTGRES_USER: webalert
    POSTGRES_PASSWORD: webalert
- name: build
  image: rust:1.45
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build

- name: test
  image: rust:1.45
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test
    - git rev-parse HEAD > .tags

- name: test migrate up
  image: rust:1.45
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    RUST_LOG: debug
    CARGO_HOME: /tmp/cargo-cache
    POSTGRES_URL: postgresql://webalert:webalert@postgres/webalert_development
  commands:
    - cargo run -- db migrate up

---
kind: pipeline
name: rust-nightly

volumes:
  - name: cargo-cache
    host:
      path: /var/lib/cargo-cache

steps:
- name: postgres
  image: postgres:12.3-alpine
  detach: true
  environment:
    POSTGRES_USER: webalert
    POSTGRES_PASSWORD: webalert
    POSTGRES_DB: webalert_development

- name: build
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build

- name: test
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test

- name: test migrate up
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    RUST_LOG: debug
    CARGO_HOME: /tmp/cargo-cache
    POSTGRES_URL: postgresql://webalert:webalert@postgres/webalert_development
  commands:
    - cargo run -- db migrate up
---
kind: signature
hmac: 86796b80092e8489a018e6f9bb0eb8134799e2143ee76dfcfc187778bf22805a

...
