[package]
name = "webalert"
version = "0.1.0"
authors = ["Mikkel Kroman <mk@maero.dk>"]
edition = "2018"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "webalert"
path = "src/main.rs"

[dependencies]
selenium-rs = "0.1.2"
structopt = "0.3.15"
log = "0.4.8"
env_logger = "0.7.1"
uuid = "0.8.1"
tokio-postgres = "0.5.4"
tokio = { version = "0.2.21", features = ["full"] }
clap = "2.33.1"
lazy_static = "1.4.0"
warp = "0.2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
