[package]
name = "webalert"
version = "0.1.0"
authors = ["Mikkel Kroman <mk@maero.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
selenium-rs = "0.1.2"
structopt = "0.3.15"
log = "0.4.8"
env_logger = "0.7.1"
