[package]
name = "webalert"
version = "0.1.0"
authors = ["Mikkel Kroman <mk@maero.dk>"]
edition = "2018"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "webalert"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33"
env_logger = { version = "0.9", default-features = false, features = ["termcolor", "atty", "humantime"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.5", default-features = false, features = [ "macros", "postgres", "chrono", "runtime-tokio-native-tls" ] }
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
warp = "0.3"

